import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>below are demo links for SSG and SSR pulling from https://jsonplaceholder.typicode.com/photos</h2>
          <ul>
            <li><Link href="/about">about page link (SSG)</Link></li>
            <li><Link href="/about2">about page 2 link (SSR)</Link></li>
          </ul>
          <br></br>
          <br></br>
        </div>
        <div>
            This is the index page, <br></br>
            <code className={styles.code}>oh look I have a class on me!</code>
          <div>
            <a
              href="#"
              target="_blank"
              rel="noopener noreferrer"
            >
              Im a link and this is an image
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
      </main>
    </>
  )
}
