import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.crotainer}>
          <h2>Below are demo links for SSG, SSR, and ISR pulling from https://www.colr.org/json/color/random</h2>
          <ul>
            <li><Link href="/renderssg">Static Site Generation(SSG)</Link></li>
            <li><Link href="/renderssr">Server Side Rendering (SSR)</Link></li>
            <li><Link href="/renderisr">Incremental Static Regeneration (ISR)</Link></li>
          </ul>
        </div>
      </main>
    </>
  )
}
